import type {
    ReviewIssue,
    ReviewResult,
    Severity,
} from '../types/review.js';

function getSeverityEmoji(severity: Severity): string {
    switch (severity) {
        case 'error':
            return '🔴';
        case 'warning':
            return '🟡';
        case 'info':
            return '🔵';
        default:
            return '⚪';
    }
}

function formatIssue(issue: ReviewIssue): string {
    const emoji = getSeverityEmoji(issue.severity);
    const lines: string[] = [];

    lines.push(
        `### ${emoji} ${issue.severity.toUpperCase()}: ${issue.file}:${issue.line}`,
    );
    lines.push('');
    lines.push(issue.message);
    lines.push('');

    if (issue.suggestion) {
        lines.push('**Suggestion:**');
        lines.push('```');
        lines.push(issue.suggestion);
        lines.push('```');
        lines.push('');
    }

    if (issue.ruleId) {
        lines.push(`*Rule: \`${issue.ruleId}\`*`);
        lines.push('');
    }

    return lines.join('\n');
}

class MarkdownFormatter {
    format(result: ReviewResult): string {
        const lines: string[] = [];

        lines.push('# Code Review Report');
        lines.push('');
        lines.push('## Summary');
        lines.push('');
        lines.push(`- **Status:** ${result.summary}`);
        lines.push(`- **Files analyzed:** ${result.filesAnalyzed}`);
        lines.push(`- **Duration:** ${result.duration}ms`);
        lines.push('');

        const errorCount = result.issues.filter(
            (i) => i.severity === 'error',
        ).length;
        const warningCount = result.issues.filter(
            (i) => i.severity === 'warning',
        ).length;
        const infoCount = result.issues.filter(
            (i) => i.severity === 'info',
        ).length;

        lines.push('| Severity | Count |');
        lines.push('|----------|-------|');
        lines.push(`| 🔴 Errors | ${errorCount} |`);
        lines.push(`| 🟡 Warnings | ${warningCount} |`);
        lines.push(`| 🔵 Info | ${infoCount} |`);
        lines.push('');

        if (result.issues.length > 0) {
            lines.push('## Issues');
            lines.push('');

            const errorIssues = result.issues.filter(
                (i) => i.severity === 'error',
            );
            const warningIssues = result.issues.filter(
                (i) => i.severity === 'warning',
            );
            const infoIssues = result.issues.filter(
                (i) => i.severity === 'info',
            );

            if (errorIssues.length > 0) {
                errorIssues.forEach((issue) => {
                    lines.push(formatIssue(issue));
                    lines.push('---');
                    lines.push('');
                });
            }

            if (warningIssues.length > 0) {
                warningIssues.forEach((issue) => {
                    lines.push(formatIssue(issue));
                    lines.push('---');
                    lines.push('');
                });
            }

            if (infoIssues.length > 0) {
                infoIssues.forEach((issue) => {
                    lines.push(formatIssue(issue));
                    lines.push('---');
                    lines.push('');
                });
            }
        } else {
            lines.push('## ✅ No issues found!');
            lines.push('');
            lines.push('Your code looks good!');
        }

        lines.push('');
        lines.push('---');
        lines.push('*Generated by [Kodus CLI](https://kodus.io)*');

        return lines.join('\n');
    }
}

export const markdownFormatter = new MarkdownFormatter();
