import { Test, TestingModule } from '@nestjs/testing';
import { CommentManagerService } from '@libs/code-review/infrastructure/adapters/services/commentManager.service';
import { PARAMETERS_SERVICE_TOKEN } from '@libs/organization/domain/parameters/contracts/parameters.service.contract';
import { MessageTemplateProcessor } from '@libs/code-review/infrastructure/adapters/services/messageTemplateProcessor.service';
import { PromptRunnerService } from '@kodus/kodus-common/llm';
import { ObservabilityService } from '@libs/core/log/observability.service';
import { PermissionValidationService } from '@libs/ee/shared/services/permissionValidation.service';
import { CodeManagementService } from '@libs/platform/infrastructure/adapters/services/codeManagement.service';
import { FileChange } from '@libs/core/infrastructure/config/types/general/codeReview.type';
import { BehaviourForNewCommits } from '@libs/core/domain/enums/code-review.enum';

jest.mock('@kodus/flow', () => ({
    createLogger: () => ({
        log: jest.fn(),
        error: jest.fn(),
        warn: jest.fn(),
        debug: jest.fn(),
        info: jest.fn(),
    }),
}));

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeFile(filename: string, patchTokens: number): Partial<FileChange> {
    const charCount = Math.floor(patchTokens * 3.5);
    const patch =
        `${filename}_` +
        'x'.repeat(Math.max(0, charCount - filename.length - 1));
    return { filename, patch, status: 'modified' } as Partial<FileChange>;
}

const START_MARKER = '<!-- kody-pr-summary:start -->';
const END_MARKER = '<!-- kody-pr-summary:end -->';
const LLM_SUMMARY = 'New summary generated by LLM.';

// ---------------------------------------------------------------------------
// Bug reproduction: REPLACE mode discards user body when tags are missing
// ---------------------------------------------------------------------------

describe('CommentManagerService – REPLACE mode bug (tags removed by user)', () => {
    let service: CommentManagerService;
    let mockObservabilityService: any;
    let mockCodeManagementService: any;
    let mockPermissionValidationService: any;

    const mockOrganizationAndTeamData = {
        organizationId: 'org-123',
        teamId: 'team-456',
    };

    const mockRepository = { id: 'repo-1', name: 'test-repo' };

    const mockPullRequest = {
        number: 42,
        title: 'Test PR',
        head: { ref: 'feature-branch', repo: { fullName: 'org/repo' } },
        base: { ref: 'main' },
    };

    beforeEach(async () => {
        mockObservabilityService = {
            runLLMInSpan: jest.fn().mockImplementation(async () => {
                return { result: LLM_SUMMARY };
            }),
        };

        mockCodeManagementService = {
            getPullRequestByNumber: jest.fn(),
        };

        mockPermissionValidationService = {
            validateBasicLicense: jest.fn().mockResolvedValue({ allowed: true }),
            getBYOKConfig: jest.fn().mockResolvedValue(null),
        };

        const module: TestingModule = await Test.createTestingModule({
            providers: [
                CommentManagerService,
                { provide: PARAMETERS_SERVICE_TOKEN, useValue: {} },
                { provide: MessageTemplateProcessor, useValue: {} },
                { provide: PromptRunnerService, useValue: {} },
                {
                    provide: ObservabilityService,
                    useValue: mockObservabilityService,
                },
                {
                    provide: PermissionValidationService,
                    useValue: mockPermissionValidationService,
                },
                {
                    provide: CodeManagementService,
                    useValue: mockCodeManagementService,
                },
            ],
        }).compile();

        service = module.get<CommentManagerService>(CommentManagerService);
    });

    // -----------------------------------------------------------------
    // Scenario: user removes the kody tags and rewrites the PR body,
    // then a new commit triggers isCommitRun with REPLACE behaviour.
    //
    // Expected: the user's text is preserved and the new summary is
    //           appended below it (same as CONCATENATE's no-tags path).
    //
    // Actual (bug): the user's text is discarded entirely.
    // -----------------------------------------------------------------

    it('should preserve the existing PR body when tags were removed by the user', async () => {
        const userRewrittenBody =
            'This is my carefully written PR description that I want to keep.';

        // PR body has NO kody markers — user removed them
        mockCodeManagementService.getPullRequestByNumber.mockResolvedValue({
            body: userRewrittenBody,
        });

        const files = [makeFile('a.ts', 100)];

        const summaryConfig = {
            generatePRSummary: true,
            behaviourForExistingDescription: 'concatenate',
            behaviourForNewCommits: BehaviourForNewCommits.REPLACE,
        };

        const result = await service.generateSummaryPR(
            mockPullRequest,
            mockRepository,
            files,
            mockOrganizationAndTeamData as any,
            'en-US',
            summaryConfig as any,
            undefined, // no byokConfig
            true, // isCommitRun = true
        );

        // The result must contain the user's original text
        expect(result).toContain(userRewrittenBody);

        // The result must also contain the new summary inside markers
        expect(result).toContain(START_MARKER);
        expect(result).toContain(LLM_SUMMARY);
        expect(result).toContain(END_MARKER);
    });

    // -----------------------------------------------------------------
    // Control test: REPLACE with tags present should work correctly
    // (this test should PASS with the current code)
    // -----------------------------------------------------------------

    it('should replace only the tagged block when tags are present', async () => {
        const userText = 'User description above the summary.';
        const oldSummary = 'Old summary content.';
        const bodyWithTags = `${userText}\n\n${START_MARKER}\n${oldSummary}\n${END_MARKER}`;

        mockCodeManagementService.getPullRequestByNumber.mockResolvedValue({
            body: bodyWithTags,
        });

        const files = [makeFile('a.ts', 100)];

        const summaryConfig = {
            generatePRSummary: true,
            behaviourForExistingDescription: 'concatenate',
            behaviourForNewCommits: BehaviourForNewCommits.REPLACE,
        };

        const result = await service.generateSummaryPR(
            mockPullRequest,
            mockRepository,
            files,
            mockOrganizationAndTeamData as any,
            'en-US',
            summaryConfig as any,
            undefined,
            true, // isCommitRun = true
        );

        // User text above the markers must be preserved
        expect(result).toContain(userText);

        // Old summary must be gone, replaced by new one
        expect(result).not.toContain(oldSummary);
        expect(result).toContain(LLM_SUMMARY);
    });

    // -----------------------------------------------------------------
    // Control test: CONCATENATE with no tags should preserve body
    // (this test should PASS with the current code)
    // -----------------------------------------------------------------

    it('CONCATENATE mode should preserve body when tags are missing', async () => {
        const userBody = 'User wrote this description.';

        mockCodeManagementService.getPullRequestByNumber.mockResolvedValue({
            body: userBody,
        });

        const files = [makeFile('a.ts', 100)];

        const summaryConfig = {
            generatePRSummary: true,
            behaviourForExistingDescription: 'concatenate',
            behaviourForNewCommits: BehaviourForNewCommits.CONCATENATE,
        };

        const result = await service.generateSummaryPR(
            mockPullRequest,
            mockRepository,
            files,
            mockOrganizationAndTeamData as any,
            'en-US',
            summaryConfig as any,
            undefined,
            true, // isCommitRun = true
        );

        expect(result).toContain(userBody);
        expect(result).toContain(START_MARKER);
        expect(result).toContain(LLM_SUMMARY);
    });
});
