export enum WorkflowType {
    CODE_REVIEW = 'CODE_REVIEW',
    CLI_CODE_REVIEW = 'CLI_CODE_REVIEW',
    CRON_CHECK_PR_APPROVAL = 'CRON_CHECK_PR_APPROVAL',
    CRON_KODY_LEARNING = 'CRON_KODY_LEARNING',
    CRON_CODE_REVIEW_FEEDBACK = 'CRON_CODE_REVIEW_FEEDBACK',
    WEBHOOK_PROCESSING = 'WEBHOOK_PROCESSING',
    CHECK_SUGGESTION_IMPLEMENTATION = 'CHECK_SUGGESTION_IMPLEMENTATION',
    AST_GRAPH_BUILD = 'AST_GRAPH_BUILD',
    AST_GRAPH_INCREMENTAL = 'AST_GRAPH_INCREMENTAL',
}
