/**
 * Real Forgejo webhook payload stubs for testing
 * Based on actual API responses from Forgejo/Gitea
 */

export const forgejoPullRequestOpenedPayload = {
    action: 'opened',
    number: 3,
    pull_request: {
        id: 3,
        url: 'https://git.example.com/kodustech/kodus-ai/pulls/3',
        number: 3,
        user: {
            id: 1,
            login: 'developer',
            login_name: '',
            full_name: 'Developer User',
            email: 'dev@example.com',
            avatar_url: 'https://git.example.com/avatars/dev.png',
            html_url: 'https://git.example.com/developer',
            username: 'developer',
        },
        title: 'feat: add new feature',
        body: 'This PR adds a new feature',
        labels: [],
        milestone: null,
        assignee: null,
        assignees: null,
        requested_reviewers: [],
        state: 'open',
        draft: false,
        comments: 0,
        review_comments: 0,
        additions: 1,
        deletions: 0,
        changed_files: 1,
        mergeable: true,
        merged: false,
        merged_at: null,
        base: {
            label: 'main',
            ref: 'main',
            sha: '8cd80e38659f5aee787e5a8ec60ffe495fb5fac6',
            repo_id: 22,
            repo: {
                id: 22,
                owner: {
                    id: 1,
                    login: 'kodustech',
                    full_name: 'Kodus Tech',
                    email: 'team@kodustech.com',
                    avatar_url: 'https://git.example.com/avatars/org.png',
                    html_url: 'https://git.example.com/kodustech',
                    username: 'kodustech',
                },
                name: 'kodus-ai',
                full_name: 'kodustech/kodus-ai',
                description: 'Kodus AI platform',
                private: true,
                fork: false,
                html_url: 'https://git.example.com/kodustech/kodus-ai',
                clone_url: 'https://git.example.com/kodustech/kodus-ai.git',
                default_branch: 'main',
            },
        },
        head: {
            label: 'feat/testing',
            ref: 'feat/testing',
            sha: '9da9e0f093815f868096d98a25ae789ec5931cac',
            repo_id: 22,
            repo: {
                id: 22,
                owner: {
                    id: 1,
                    login: 'kodustech',
                    full_name: 'Kodus Tech',
                    email: 'team@kodustech.com',
                    avatar_url: 'https://git.example.com/avatars/org.png',
                    html_url: 'https://git.example.com/kodustech',
                    username: 'kodustech',
                },
                name: 'kodus-ai',
                full_name: 'kodustech/kodus-ai',
                description: 'Kodus AI platform',
                private: true,
                fork: false,
                html_url: 'https://git.example.com/kodustech/kodus-ai',
                clone_url: 'https://git.example.com/kodustech/kodus-ai.git',
                default_branch: 'main',
            },
        },
        created_at: '2026-02-02T22:52:17+11:00',
        updated_at: '2026-02-02T22:52:17+11:00',
    },
    repository: {
        id: 22,
        owner: {
            id: 1,
            login: 'kodustech',
            full_name: 'Kodus Tech',
            email: 'team@kodustech.com',
            avatar_url: 'https://git.example.com/avatars/org.png',
            html_url: 'https://git.example.com/kodustech',
            username: 'kodustech',
        },
        name: 'kodus-ai',
        full_name: 'kodustech/kodus-ai',
        description: 'Kodus AI platform',
        private: true,
        fork: false,
        html_url: 'https://git.example.com/kodustech/kodus-ai',
        clone_url: 'https://git.example.com/kodustech/kodus-ai.git',
        default_branch: 'main',
    },
    sender: {
        id: 1,
        login: 'developer',
        full_name: 'Developer User',
        email: 'dev@example.com',
        avatar_url: 'https://git.example.com/avatars/dev.png',
        html_url: 'https://git.example.com/developer',
        username: 'developer',
    },
};

export const forgejoIssueCommentPayload = {
    action: 'created',
    issue: {
        id: 3,
        url: 'https://git.example.com/api/v1/repos/kodustech/kodus-ai/issues/3',
        html_url: 'https://git.example.com/kodustech/kodus-ai/pulls/3',
        number: 3,
        user: {
            id: 1,
            login: 'developer',
            full_name: 'Developer User',
            email: 'dev@example.com',
            avatar_url: 'https://git.example.com/avatars/dev.png',
            html_url: 'https://git.example.com/developer',
            username: 'developer',
        },
        title: 'feat: readme',
        body: '',
        labels: [],
        milestone: null,
        assignee: null,
        assignees: null,
        state: 'open',
        comments: 1,
        created_at: '2026-02-02T22:52:17+11:00',
        updated_at: '2026-02-03T19:11:03+11:00',
        closed_at: null,
        pull_request: {
            merged: false,
            merged_at: null,
            draft: false,
            html_url: 'https://git.example.com/kodustech/kodus-ai/pulls/3',
        },
        repository: {
            id: 22,
            name: 'kodus-ai',
            owner: 'kodustech',
            full_name: 'kodustech/kodus-ai',
        },
    },
    pull_request: {
        id: 3,
        url: 'https://git.example.com/kodustech/kodus-ai/pulls/3',
        number: 3,
        user: {
            id: 1,
            login: 'developer',
            full_name: 'Developer User',
            email: 'dev@example.com',
            avatar_url: 'https://git.example.com/avatars/dev.png',
            html_url: 'https://git.example.com/developer',
            username: 'developer',
        },
        title: 'feat: readme',
        body: '',
        state: 'open',
        draft: false,
        html_url: 'https://git.example.com/kodustech/kodus-ai/pulls/3',
        base: {
            label: 'main',
            ref: 'main',
            sha: '8cd80e38659f5aee787e5a8ec60ffe495fb5fac6',
            repo: {
                id: 22,
                name: 'kodus-ai',
                full_name: 'kodustech/kodus-ai',
                owner: {
                    id: 1,
                    login: 'kodustech',
                    username: 'kodustech',
                },
            },
        },
        head: {
            label: 'feat/testing',
            ref: 'feat/testing',
            sha: '9da9e0f093815f868096d98a25ae789ec5931cac',
            repo: {
                id: 22,
                name: 'kodus-ai',
                full_name: 'kodustech/kodus-ai',
                owner: {
                    id: 1,
                    login: 'kodustech',
                    username: 'kodustech',
                },
            },
        },
    },
    comment: {
        id: 8,
        html_url:
            'https://git.example.com/kodustech/kodus-ai/pulls/3#issuecomment-8',
        pull_request_url: 'https://git.example.com/kodustech/kodus-ai/pulls/3',
        issue_url: '',
        user: {
            id: 1,
            login: 'developer',
            full_name: 'Developer User',
            email: 'dev@example.com',
            avatar_url: 'https://git.example.com/avatars/dev.png',
            html_url: 'https://git.example.com/developer',
            username: 'developer',
        },
        body: '@kody please review this',
        created_at: '2026-02-03T19:11:03+11:00',
        updated_at: '2026-02-03T19:11:03+11:00',
    },
    repository: {
        id: 22,
        owner: {
            id: 1,
            login: 'kodustech',
            full_name: 'Kodus Tech',
            email: 'team@kodustech.com',
            avatar_url: 'https://git.example.com/avatars/org.png',
            html_url: 'https://git.example.com/kodustech',
            username: 'kodustech',
        },
        name: 'kodus-ai',
        full_name: 'kodustech/kodus-ai',
        description: 'Kodus AI platform',
        private: true,
        fork: false,
        html_url: 'https://git.example.com/kodustech/kodus-ai',
        clone_url: 'https://git.example.com/kodustech/kodus-ai.git',
        default_branch: 'main',
    },
    sender: {
        id: 1,
        login: 'developer',
        full_name: 'Developer User',
        email: 'dev@example.com',
        avatar_url: 'https://git.example.com/avatars/dev.png',
        html_url: 'https://git.example.com/developer',
        username: 'developer',
    },
    is_pull: true,
};

export const forgejoPullRequestReviewCommentPayload = {
    action: 'created',
    pull_request: {
        id: 3,
        number: 3,
        title: 'feat: add new feature',
        state: 'open',
    },
    comment: {
        id: 1,
        body: 'This looks good!',
        path: 'src/index.ts',
        commit_id: '9da9e0f093815f868096d98a25ae789ec5931cac',
        user: {
            id: 1,
            login: 'reviewer',
            username: 'reviewer',
        },
        created_at: '2026-02-02T22:52:17+11:00',
        updated_at: '2026-02-02T22:52:17+11:00',
    },
    repository: {
        id: 22,
        name: 'kodus-ai',
        full_name: 'kodustech/kodus-ai',
        owner: {
            id: 1,
            login: 'kodustech',
            username: 'kodustech',
        },
    },
    sender: {
        id: 2,
        login: 'reviewer',
        username: 'reviewer',
    },
};
